# DATABASE
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}


spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GMAIL SMTP CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# GEMINI CONFIGURATION
gemini.api.key=${GEMINI_API_KEY:}

# VNPAY GATEWAY CONFIGURATION
vnp.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.tmn-code=3EZP4RX2
vnp.hash-secret=WY8I3BKD7QW4BQ3TDYH15WX0HQVIU7QM
vnp.return-url=http://localhost:3000/payment/vnpay-callback

# SUPABASE STORAGE
supabase.url=https://igqxplizbdyozagsaajg.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlncXhwbGl6YmR5b3phZ3NhYWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2OTU4OTMsImV4cCI6MjA5ODI3MTg5M30.xX3zFOhSfoo_GTpixKKzAW0ywHWReGYDiRRMV_pN1rw
supabase.bucket=agrimarket

# AGORA VIDEO STREAMING CONFIGURATION
agora.app-id=${AGORA_APP_ID:}
agora.app-certificate=${AGORA_APP_CERTIFICATE:}

# GIAO HANG NHANH CONFIGURATION
ghn.api.token=${GHN_API_TOKEN:}
ghn.api.shopid=${GHN_API_SHOPID:}
ghn.api.url=${GHN_API_URL:https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create}
# Bật/tắt chế độ giả lập hành trình giao hàng nhanh
ghn.simulation.enabled=${GHN_SIMULATION_ENABLED:false}


