# DATABASE
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=AgriMarketplace;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:123456}


spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# GMAIL SMTP CONFIGURATION
# Vui lòng thay thế bằng Gmail và Mật khẩu ứng dụng (App Password) của bạn
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# GEMINI CONFIGURATION
gemini.api.key=${GEMINI_API_KEY:}

# VNPAY GATEWAY CONFIGURATION
vnp.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnp.tmn-code=3EZP4RX2
vnp.hash-secret=WY8I3BKD7QW4BQ3TDYH15WX0HQVIU7QM
vnp.return-url=http://localhost:3000/payment/vnpay-callback
